In [9]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [10]:
import pandas as pd
from src.utils.file_utils import fetch_file 
CUSTOMER_URL = "https://drive.google.com/file/d/1Js2P2OX65L0mfWRv63g7z-XAv30fHl7r/view?usp=share_link"
GEOLOCATION_URL = "https://drive.google.com/file/d/14pNzmp4Efr0NBJyCATceyDkRW_XzvTLQ/view?usp=share_link"
ORDER_ITEMS_URL = "https://drive.google.com/file/d/1jLHg1ePMZw9tZ1S_b8JZBjTlSWzpTRU-/view?usp=share_link"
ORDER_PAYMENTS_URL = "https://drive.google.com/file/d/1WAhjEt29Q3tsXqShpgMTq-6qNdeXM3St/view?usp=share_link"
REVIEWS_URL = "https://drive.google.com/file/d/15vPOEMjN2nDKs5_1I1fSaktsDE-e_ftW/view?usp=share_link"
ORDERS_URL = "https://drive.google.com/file/d/1jyFUxKFJFGZiHHf-7QuphbKvr5LsGtZR/view?usp=share_link"
PRODUCTS_URL = "https://drive.google.com/file/d/18GWfqup9MmsxA8KtD_-s-RYSyL1Ec-nm/view?usp=share_link"
CUSTOMER_URL = "https://drive.google.com/file/d/1QNWrPqOn3Cxbj0qyOzm6p4Dsqp5SDyyg/view?usp=share_link"
CATEGORIES_URL = "https://drive.google.com/file/d/1fQuNKaCxOjMqsCOrhwpGQ7Y9slmrrUCC/view?usp=share_link"

In [11]:
#Fetching data from google drive
df_customer = fetch_file(CUSTOMER_URL)
df_geolocation = fetch_file(GEOLOCATION_URL)
df_order_items = fetch_file(ORDER_ITEMS_URL)
df_order_payments = fetch_file(ORDER_PAYMENTS_URL)
df_reviews = fetch_file(REVIEWS_URL)
df_orders = fetch_file(ORDERS_URL)
df_products = fetch_file(PRODUCTS_URL)
df_categories = fetch_file(CATEGORIES_URL)

Downloading...
From: https://drive.google.com/uc?id=1QNWrPqOn3Cxbj0qyOzm6p4Dsqp5SDyyg
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmplemvmdhh/file.csv
100%|██████████| 175k/175k [00:00<00:00, 8.18MB/s]

✅ Archivo cargado → 3095 filas, 4 columnas

Downloading...
From: https://drive.google.com/uc?id=14pNzmp4Efr0NBJyCATceyDkRW_XzvTLQ
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpw9awisvr/file.csv
100%|██████████| 61.3M/61.3M [00:04<00:00, 13.6MB/s]

✅ Archivo cargado → 1000163 filas, 5 columnas

Downloading...
From: https://drive.google.com/uc?id=1jLHg1ePMZw9tZ1S_b8JZBjTlSWzpTRU-
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpfce4swy3/file.csv
100%|██████████| 15.4M/15.4M [00:03<00:00, 5.01MB/s]

✅ Archivo cargado → 112650 filas, 7 columnas

Downloading...
From: https://drive.google.com/uc?id=1WAhjEt29Q3tsXqShpgMTq-6qNdeXM3St
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpyy2mbmr7/file.csv
100%|██████████| 5.78M/5.78M [00:00<00:00, 18.9MB/s]

✅ Archivo cargado → 103886 filas, 5 columnas

Downloading...
From: https://drive.google.com/uc?id=15vPOEMjN2nDKs5_1I1fSaktsDE-e_ftW
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpj3cxiy7d/file.csv
100%|██████████| 14.5M/14.5M [00:01<00:00, 14.4MB/s]

✅ Archivo cargado → 99224 filas, 7 columnas

Downloading...
From: https://drive.google.com/uc?id=1jyFUxKFJFGZiHHf-7QuphbKvr5LsGtZR
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpul4tr2n4/file.csv
100%|██████████| 17.7M/17.7M [00:00<00:00, 20.6MB/s]

✅ Archivo cargado → 99441 filas, 8 columnas

Downloading...
From: https://drive.google.com/uc?id=18GWfqup9MmsxA8KtD_-s-RYSyL1Ec-nm
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpr1qiv2z_/file.csv
100%|██████████| 2.38M/2.38M [00:00<00:00, 9.65MB/s]

✅ Archivo cargado → 32951 filas, 9 columnas

Downloading...
From: https://drive.google.com/uc?id=1fQuNKaCxOjMqsCOrhwpGQ7Y9slmrrUCC
To: /var/folders/hb/n_q78zrx4h72f7qw8pjwrwx80000gn/T/tmpxqtj8lup/file.csv
100%|██████████| 2.61k/2.61k [00:00<00:00, 6.72MB/s]

✅ Archivo cargado → 71 filas, 2 columnas

In [ ]:
df_customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
df_customer.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [ ]:
df_customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB